// Generated by https://quicktype.io

export interface RespAlertas {
    data:  Alertas[];
    pages: number;
}
export interface Alertas {
    observacion:   string;
    fechaRegistro: string;
    nombres:       string;
    apellidos:     string;
    razonSocial:   string;
}