// Generated by https://quicktype.io

export interface RespBuscarConductores {
    data:  ConductorSearch[];
    pages: number;
    pagesExcel?: number
    last_page: number;
}
export interface RespBuscarConductoresSecretaria {
    data:  ConductorSearchSecretaria[];
    pages: number;
    pagesExcel?: number
    last_page: number;
}

export interface ConductorSearch {
  id:             string;
  nombres:                 string;
  apellidos:               string;
  cedula:                  string;
  telefono:                string;
  licenciaConduccion:      string;
  categoriaPase:           string;
  fotoURL:                     string;


  fechaLicenciaConduccion: Date;
  idEps:                   number;
  idArl:                   number;
  idAfp:                   number;
  ultima_vinculacion: {
    id: string;
    fechaUltimaRefrendacion: Date;
    vehiculo: {
      placa: string;
      tarjetaOperacion: string;
      fechaTarjetaOperacionF: Date
    }
  }
}

export interface ConductorSearchSecretaria {
    id:             string;
    nombres:                 string;
    cedula:                  string;
    direccion:               string;
    telefono:                string;
    licenciaConduccion:      string;
    fechaLicenciaConduccion: string;
    categoriaPase:           string;
    tipoSangre:              string;
    fechaNacimiento:         string;
    fotoURL:                 string;
    fechaTarjetaOperacionF:   Date;
    fechaTarjetaOperacion:    Date;
    fechaNumeroRCC:           Date;
    fechaNumeroRCE:           Date;
    fechaNumeroSOAT:          Date;
    fechaNumeroTecnoMecanica: Date;


    idEps:                   number;
    idArl:                   number;
    idAfp:                   number;
    ultima_vinculacion: {
      id: string;
      vehiculo: {
        fechaTarjetaOperacionF:  Date;
        tarjetaOperacion:        string;
        numeroRCC:               string;
        numeroRCE:               string;
        numeroSOAT:              string;
        numeroTecnoMecanica:     string;
        nombrePropietario:       string;
        cedulaPropietario:       string;
        direccionPropietario:    string;
        telefonoPropietario:     string;
        placa:                   string;
        modelo:                  string;
        numeroMotor:             string;
        numeroChasis:            string;
      }
    }
}
